name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "ci-cd"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
